"""fight_model cactbot annotations

Revision ID: 8ac127cddffe
Revises: 267acc60ac83
Create Date: 2026-05-24 21:09:23.811752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac127cddffe'
down_revision: Union[str, None] = '267acc60ac83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fight_model', sa.Column('cactbot_label', sa.Text(), nullable=True))
    op.add_column('fight_model', sa.Column('cactbot_phase_label', sa.Text(), nullable=True))
    op.add_column('fight_model', sa.Column('cactbot_expected_t_ms', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fight_model', 'cactbot_expected_t_ms')
    op.drop_column('fight_model', 'cactbot_phase_label')
    op.drop_column('fight_model', 'cactbot_label')
    # ### end Alembic commands ###
