"""initial schema (T-003)

Revision ID: ab0d3c6000ed
Revises: 
Create Date: 2026-05-23 20:18:14.649095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab0d3c6000ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('fight_id', sa.BigInteger(), nullable=False),
    sa.Column('module', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('fight_id', 'module')
    )
    op.create_table('fault_scores',
    sa.Column('fight_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('fight_id', 'player_id')
    )
    op.create_table('fight_model',
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ability_game_id', sa.Integer(), nullable=True),
    sa.Column('relative_t_ms', sa.BigInteger(), nullable=True),
    sa.Column('time_variance_ms', sa.BigInteger(), nullable=True),
    sa.Column('type_label', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('encounter_id', 'version', 'phase', 'seq')
    )
    op.create_table('prog_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('fight_percentage', sa.Numeric(), nullable=True),
    sa.Column('pull_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('strat_config',
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_ref', sa.Text(), nullable=False),
    sa.Column('assignments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mit_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('encounter_id', 'mechanic_ref')
    )
    op.create_table('fights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_code', sa.Text(), nullable=False),
    sa.Column('fight_id_in_report', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('is_kill', sa.Boolean(), nullable=True),
    sa.Column('fight_percentage', sa.Numeric(), nullable=True),
    sa.Column('last_phase', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['report_code'], ['reports.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_code', 'fight_id_in_report', name='uq_fights_report_fight')
    )
    op.create_index('ix_fights_encounter_id', 'fights', ['encounter_id'], unique=False)
    op.create_table('ingestion_ledger',
    sa.Column('report_code', sa.Text(), nullable=False),
    sa.Column('fights_ingested', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('last_event_ts', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_code'], ['reports.code'], ),
    sa.PrimaryKeyConstraint('report_code')
    )
    op.create_table('combatants',
    sa.Column('fight_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('server', sa.Text(), nullable=True),
    sa.Column('job', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ),
    sa.PrimaryKeyConstraint('fight_id', 'player_id')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fight_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ability_game_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_ability_game_id', 'events', ['ability_game_id'], unique=False)
    op.create_index('ix_events_fight_ts', 'events', ['fight_id', 'ts'], unique=False)
    op.create_index('ix_events_fight_type', 'events', ['fight_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_fight_type', table_name='events')
    op.drop_index('ix_events_fight_ts', table_name='events')
    op.drop_index('ix_events_ability_game_id', table_name='events')
    op.drop_table('events')
    op.drop_table('combatants')
    op.drop_table('ingestion_ledger')
    op.drop_index('ix_fights_encounter_id', table_name='fights')
    op.drop_table('fights')
    op.drop_table('strat_config')
    op.drop_table('reports')
    op.drop_table('prog_points')
    op.drop_table('fight_model')
    op.drop_table('fault_scores')
    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
