"""t_108_abilities_and_labels

Revision ID: eb34cac3f775
Revises: 8f2f3edb79f7
Create Date: 2026-05-23 21:45:14.680258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb34cac3f775'
down_revision: Union[str, None] = '8f2f3edb79f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('ability_game_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ability_game_id')
    )
    op.create_table('ability_labels',
    sa.Column('ability_game_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ability_game_id'], ['abilities.ability_game_id'], ),
    sa.PrimaryKeyConstraint('ability_game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ability_labels')
    op.drop_table('abilities')
    # ### end Alembic commands ###
